#!/usr/bin/env bash

BIN=wildwater

usage() {
    echo "Usage:"
    echo "  $0 <csv_file> histo <max|src|real>"
    exit 1
}

[ $# -ne 3 ] && usage

CSV="$1"
CMD="$2"
TYPE="$3"

[ ! -f "$CSV" ] && echo "CSV file not found" && exit 1

if [ ! -x "$BIN" ]; then
    make || exit 1
fi

START=$(date +%s%N)

case "$CMD" in
    histo)
        case "$TYPE" in
            max|src|real)
                ./"$BIN" "$CSV" histo "$TYPE" || exit 1
                ;;
            *)
                usage
                ;;
        esac
        ;;
    *)
        usage
        ;;
esac

case "$TYPE" in
    max)
        gnuplot -c plot_max.gp histo_max.dat histo_max.png
        ;;
    src)
        gnuplot -c plot_src.gp histo_src.dat histo_src.png
        ;;
    real)
        gnuplot -c plot_real.gp histo_real.dat histo_real.png
        ;;
esac

END=$(date +%s%N)
echo "Execution time: $(( (END-START)/1000000 )) ms"
